version: '3.8'

services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sw-planets-api
    ports:
      - "8080:8080"
    depends_on:
      - mysql-container
  mysql-container:
    image: mysql:8.3.0
    container_name: mysql-container-starwars
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: starwars
      MYSQL_USER: starwars
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"

volumes:
  mysql-data:
